project:
  type: website

website:
  title: "CS6304"
  favicon: icon.png
  navbar:
    background: "#630031"
    foreground: "#CF4420"
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
    linkcolor: "#CF4420"



